### ISSUE TITLE
Best way to handle redirect to subscriptionURL

### ISSUE THREAD

**Issue by devopsangel** [ctrlaltdylan/shopify-session-tokens-nextjs#3]
@ctrlaltdylan thanks for the frame! Love it!

q.q. during callback if I want to redirect to `confirmationUrl` what would be the best way? This is what I tried

```
    const afterAuth = async (req, res, accessToken) => {
    const { shop } = req.query;
    const { access_token } = accessToken;
    // console.log(`Shop: ${shop}; AccessToken: ${JSON.stringify(accessToken)}`);

    const installResponse = await installApp(
        access_token,
        shop,
        APP_HOST,
        SHOPIFY_API_VERSION,
    );

    // present user with billing options
    if (installResponse.status === 201) {
        await getSubscriptionUrl(res, access_token, shop, APP_HOST, SHOPIFY_API_VERSION);
    }
};

export default handleAuthCallback(afterAuth);
```

from  `getSubscriptionUrl` I return

```
   ...
   ...
   const response = await fetch(`https://${shop}/admin/api/${apiVersion}/graphql.json`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-Shopify-Access-Token': accessToken,
        },
        body: query,
    });

    const responseJson = await response.json();
    const confirmationUrl = responseJson.data.appSubscriptionCreate.confirmationUrl;

    return res.redirect(confirmationUrl);
```

and I am getting this issue

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at setHeadersFromObject (/Users/app/node_modules/next/dist/compiled/compression/index.js:1:155900)
    at ServerResponse.setWriteHeadHeaders (/Users/app/node_modules/next/dist/compiled/compression/index.js:1:156134)
    at ServerResponse.writeHead (/Users/app/node_modules/next/dist/compiled/compression/index.js:1:155341)
    at redirect (/Users/app/node_modules/next/dist/next-server/server/api-utils.js:27:357)
    at ServerResponse.apiRes.redirect (/Users/app/node_modules/next/dist/next-server/server/api-utils.js:6:354)
    at _callee$ (/Users/app/node_modules/shopify-nextjs-toolbox/lib/middleware/oauth/handleAuthCallback.js:58:19)
    at tryCatch (/Users/app/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/app/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/app/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
```

**Comment by ctrlaltdylan** [comment]
The OAuth flow was built with the opinion that it would redirect back to the `process.env.HOME_PAGE` environment variable and described on the docs:

https://github.com/ctrlaltdylan/shopify-session-tokens-nextjs

```

// pages/api/auth/callback.js
import { handleAuthCallback } from 'shopify-nextjs-toolbox';

const afterAuth = async(req, res, accessToken) => {
  // save accessToken with the shop
  db.collection('shop').insertOne({name: req.query.shop, accessToken});

  // redirect is handled by handleAuthCallback, no need to res.send() or res.redirect() here.
};

export default handleAuthCallback(afterAuth);
```

You're getting that error because `res.redirect` is called outside of this middleware function. But I see your other PR on the toolbox repo itself and I'll bring the conversation over there.
