### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by Bijig0** [ctrlaltdylan/shopify-session-tokens-nextjs#6]
Launching the project on my localhost with `npm run dev` leaves me with a blank screen. 

If I open the ngrok tunnel through the Shopify Partners app, it correctly shows the page for a second then refreshes to this error. 
![image](https://user-images.githubusercontent.com/76978374/117086470-eb078800-ad8f-11eb-92ce-4ac9b82e2469.png)

**Comment by Bijig0** [comment]
I think it has something to do with the auth.
 Going to `<>.ngrok.io/api/auth` gives `TypeError: Cannot read property 'shop' of undefined
    at _default (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\shopify-nextjs-toolbox\lib\middleware\oauth\handleAuthStart.js:17:14)
    at apiResolver (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\next\dist\next-server\server\api-utils.js:8:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DevServer.handleApiRequest (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\next\dist\next-server\server\next-server.js:62:403)
    at async Object.fn (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\next\dist\next-server\server\next-server.js:54:176)
    at async Router.execute (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\next\dist\next-server\server\router.js:23:67)
    at async DevServer.run (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\next\dist\next-server\server\next-server.js:63:656)
    at async DevServer.handleRequest (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\next\dist\next-server\server\next-server.js:33:242)`

going to `<>.ngrok.io/api/auth/callback` gives the error `TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at Function.byteLength (buffer.js:728:11)
    at safeCompare (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\shopify-nextjs-toolbox\lib\middleware\oauth\safeCompare.js:13:21)
    at verifyHmac (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\shopify-nextjs-toolbox\lib\middleware\oauth\verifyHmac.js:33:38)
    at _callee$ (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\shopify-nextjs-toolbox\lib\middleware\oauth\handleAuthCallback.js:28:50)
    at tryCatch (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\brady\shopify-session-tokens-nextjs\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\brady\shopify-session-tokens-nextjs\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7 {
  code: 'ERR_INVALID_ARG_TYPE'`

**Comment by hankmander** [comment]
Maybe related to the [issue](https://github.com/ctrlaltdylan/shopify-session-tokens-nextjs/issues/4) I had. Check out [this PR](https://github.com/ctrlaltdylan/shopify-session-tokens-nextjs/pull/5) that does the redirect using the Shopify App Bridge.
